---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: bom-demo
spec:
  description: |
    This pipeline is a demo of bom in running a CICD environment.
  params:
  - name: repo-url
    type: string
    description: The git repository URL to clone from.
  - name: branch-name
    type: string
    description: The git branch to clone.
  workspaces:
  - name: shared-data
    description: |
      This workspace will receive the cloned git repo and be passed
      to the next Task for the repo's README.md file to be read.
  - name: dockerconfig
    description: Docker credential
  tasks:
  - name: clone-repository
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: $(params.branch-name)
  - name: build-image
    runAfter: ["clone-repository"]
    taskRef:
      name: kaniko
    workspaces:
    - name: source
      workspace: shared-data
    - name: dockerconfig
      workspace: dockerconfig
    params:
    - name: DOCKERFILE
      value: $(workspaces.source.path)/actions/broker/Dockerfile
    - name: IMAGE
      value: ghcr.io/uservers/miniprow/miniprow:beta
  - name: sbom
    runAfter: ["build-image"]  # Wait until the clone is done before reading the readme.
    taskRef:
      name: sbom
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: namespace
      value: https://github.com/uservers/miniprow
    - name: EXTRA_ARGS
      value: 
      - $(workspaces.source.path)
      - "-ighcr.io/uservers/miniprow/miniprow:beta"
      - "-o$(workspaces.source.path)/sbom.spdx"
  - name: cosign
    runAfter: ["sbom"]
    workspaces:
    - name: source
      workspace: shared-data
    - name: dockerconfig
      workspace: dockerconfig
    taskSpec:
      workspaces:
      - name: source
      - name: dockerconfig
      steps:
      - image: gcr.io/projectsigstore/cosign:v1.0.0
        env:
        - name: DOCKER_CONFIG
          value: "$(workspaces.dockerconfig.path)"
        args:
        - attach
        - sbom
        - "-sbom"
        - "$(workspaces.source.path)/sbom.spdx"
        - ghcr.io/uservers/miniprow/miniprow:beta
  - name: cat-readme
    runAfter: ["sbom"]  # Wait until the clone is done before reading the readme.
    workspaces:
    - name: source
      workspace: shared-data
    taskSpec:
      workspaces:
      - name: source
      steps:
      - image: zshusers/zsh:4.3.15
        script: |
          #!/usr/bin/env zsh
          cat $(workspaces.source.path)/README.md
          cat $(workspaces.source.path)/sbom.spdx
