---
#
# Build a generic secret from a docker config
# kubectl create secret generic regcred --from-file=config.json=/home/urbano/.docker/config2.json 
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-sa
secrets:
  - name: regcred

